
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action BoardAction;
		
		private global::Gtk.Action EngineAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action QuitAction;
		
		private global::Gtk.Action LoadFENAction;
		
		private global::Gtk.Action LoadEngineAction;
		
		private global::Gtk.Action AboutAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar MenuBar;
		
		private global::Gtk.DrawingArea drawingarea1;
		
		private global::Gtk.Entry MoveEntry;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GUI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.FileAction, "<Alt><Mod2>f");
			this.BoardAction = new global::Gtk.Action ("BoardAction", global::Mono.Unix.Catalog.GetString ("_Board"), null, null);
			this.BoardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Board");
			w1.Add (this.BoardAction, "<Alt><Mod2>b");
			this.EngineAction = new global::Gtk.Action ("EngineAction", global::Mono.Unix.Catalog.GetString ("_Engine"), null, null);
			this.EngineAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Engine");
			w1.Add (this.EngineAction, "<Alt><Mod2>e");
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
			w1.Add (this.HelpAction, "<Alt><Mod2>h");
			this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, null);
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
			w1.Add (this.QuitAction, "<Primary><Mod2>q");
			this.LoadFENAction = new global::Gtk.Action ("LoadFENAction", global::Mono.Unix.Catalog.GetString ("Load _FEN"), null, null);
			this.LoadFENAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load _FEN");
			w1.Add (this.LoadFENAction, "<Primary><Mod2>f");
			this.LoadEngineAction = new global::Gtk.Action ("LoadEngineAction", global::Mono.Unix.Catalog.GetString ("_Load Engine"), null, null);
			this.LoadEngineAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Load Engine");
			w1.Add (this.LoadEngineAction, "<Primary><Mod2>e");
			this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("_About"), null, null);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
			w1.Add (this.AboutAction, "<Primary><Mod2>a");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "GUI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Gandalf Chess GUI");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GUI.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='MenuBar'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='BoardAction' action='BoardAction'><menuitem name='LoadFENAction' action='LoadFENAction'/></menu><menu name='EngineAction' action='EngineAction'><menuitem name='LoadEngineAction' action='LoadEngineAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
			this.MenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MenuBar")));
			this.MenuBar.Name = "MenuBar";
			this.vbox1.Add (this.MenuBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MenuBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.vbox1.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.drawingarea1]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.MoveEntry = new global::Gtk.Entry ();
			this.MoveEntry.CanFocus = true;
			this.MoveEntry.Name = "MoveEntry";
			this.MoveEntry.IsEditable = true;
			this.MoveEntry.MaxLength = 5;
			this.MoveEntry.InvisibleChar = '•';
			this.vbox1.Add (this.MoveEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MoveEntry]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 457;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.QuitAction.Activated += new global::System.EventHandler (this.OnQuit);
			this.LoadFENAction.Activated += new global::System.EventHandler (this.OnLoadFEN);
			this.LoadEngineAction.Activated += new global::System.EventHandler (this.OnLoadEngine);
		}
	}
}
