
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class PawnPromotionDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.RadioButton QueenButton;
		
		private global::Gtk.RadioButton RookButton;
		
		private global::Gtk.RadioButton BishopButton;
		
		private global::Gtk.RadioButton KnightButton;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GUI.PawnPromotionDialog
			this.WidthRequest = 350;
			this.HeightRequest = 125;
			this.Name = "GUI.PawnPromotionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child GUI.PawnPromotionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Ypad = 13;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Please select a piece type to promote to.");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.QueenButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Queen"));
			this.QueenButton.CanFocus = true;
			this.QueenButton.Name = "QueenButton";
			this.QueenButton.Active = true;
			this.QueenButton.DrawIndicator = true;
			this.QueenButton.UseUnderline = true;
			this.QueenButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox1.Add (this.QueenButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.QueenButton]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.RookButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Rook"));
			this.RookButton.CanFocus = true;
			this.RookButton.Name = "RookButton";
			this.RookButton.DrawIndicator = true;
			this.RookButton.UseUnderline = true;
			this.RookButton.Group = this.QueenButton.Group;
			this.hbox1.Add (this.RookButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.RookButton]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BishopButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Bishop"));
			this.BishopButton.CanFocus = true;
			this.BishopButton.Name = "BishopButton";
			this.BishopButton.DrawIndicator = true;
			this.BishopButton.UseUnderline = true;
			this.BishopButton.Group = this.QueenButton.Group;
			this.hbox1.Add (this.BishopButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BishopButton]));
			w5.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.KnightButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Knight"));
			this.KnightButton.CanFocus = true;
			this.KnightButton.Name = "KnightButton";
			this.KnightButton.DrawIndicator = true;
			this.KnightButton.UseUnderline = true;
			this.KnightButton.Group = this.QueenButton.Group;
			this.hbox1.Add (this.KnightButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.KnightButton]));
			w6.Position = 3;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child GUI.PawnPromotionDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 350;
			this.DefaultHeight = 125;
			this.Show ();
		}
	}
}
